### ISSUE TITLE
AVM Module Review

### ISSUE THREAD

**Issue by mbilalamjad** [Azure/terraform-azurerm-avm-res-containerregistry-registry#3]
Hi @pradorodriguez

Performed a review of the module and have the following recommendations.

1. terraform.lock.hcl shouldn't be in the repo per the .gitignore file.
2. Update the support.md file.
3. Consider following specs TFNFR31 for the local.tf file.
4. Consider updating version to 0.1.0 as the first version that would be published into the terraform registry per spec SNFR17.
5. Consider updating output to contain Resource Name, ID and Object per specs RMFR7 & TFFR2.
6. Consider setting prevent_deletion_if_contains_resources to false in provider block in example code per spec TFNFR36.
7. Consider setting a constraint on maximum major version of Provider per spec TFNFR26.
8. The Contributor and Owner teams are not added to the repo per spec SNFR20.

Once you action the above you should be good to publish to the terraform registry

**Comment by kewalaka** [comment]
i wonder if the intent was to leave this open until the avm core team had completed their review?  @mbilalamjad how do things look following the changes in the attached PR?

**Comment by mbilalamjad** [comment]
Hey @kewalaka and @pradorodriguez, thank you for the PR

Reopening this issue and updating the feedback based on the latest PR

- [ ] 1 - terraform.lock.hcl shouldn't be in the repo per the .gitignore file.
- [ ] 2 - Update the support.md file.
- [x] 3 - Consider following specs TFNFR31 for the local.tf file.
- [x] 4 - Consider updating version to 0.1.0 as the first version that would be published into the terraform registry per spec SNFR17.
- [x] 5 - Consider updating output to contain Resource Name, ID and Object per specs RMFR7 & TFFR2.
- [x] 6 - Consider setting prevent_deletion_if_contains_resources to false in provider block in example code per spec TFNFR36.
- [ ] 7 - Consider setting a constraint on maximum major version of Provider per spec TFNFR26.
- [ ] 8 - The Contributor and Owner teams are not added to the repo per spec SNFR20.

Regarding 1, From the commit that you've mentioned, please see the [.gitignore file](https://github.com/Azure/terraform-azurerm-avm-template/blob/68ebe040baeda0416976a6776cecbcf96d1c8909/.gitignore) in which the .terraform.lock.hcl should be ignored whereas its currently present in the [repo](https://github.com/Azure/terraform-azurerm-avm-res-containerregistry-registry)

Regarding 7, please see file [terraform.tf file](https://github.com/Azure/terraform-azurerm-avm-res-containerregistry-registry/blob/main/terraform.tf)

**Comment by kewalaka** [comment]
#4 addresses point one.

Point 7 i'm confused about, there already is a major version on both providers:

```terraform
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.71.0, < 4.0.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.5.0, < 4.0.0"
    }
```

both are capped at v4.

**Comment by kewalaka** [comment]
@pradorodriguez I need your help with the editing of support.md - that looks like an internal MSFT ask.

**Comment by mbilalamjad** [comment]
> #4 addresses point one.
> 
> Point 7 i'm confused about, there already is a major version on both providers:
> 
> ```terraform
>     azurerm = {
>       source  = "hashicorp/azurerm"
>       version = ">= 3.71.0, < 4.0.0"
>     }
>     random = {
>       source  = "hashicorp/random"
>       version = ">= 3.5.0, < 4.0.0"
>     }
> ```
> 
> both are capped at v4.

looks good, just updated the review task list in my comment above

**Comment by kewalaka** [comment]
@mbilalamjad I've just updated the support.md based on feedback from @pradorodriguez - also in PR #5 

I think that addresses all comments raised.

**Comment by mbilalamjad** [comment]
Thank you @kewalaka and @pradorodriguez for the updates, I reviewed/approved the latest PR for you to merge and publish this module to the terraform registry.
