### ISSUE TITLE
[AVM Module Issue]: Add encryption of ACR

### ISSUE THREAD

**Issue by piotrkurylak** [Azure/terraform-azurerm-avm-res-containerregistry-registry#34]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### (Optional) Module Version

0.1.0

### Description

Hi there,

First of all, thanks for your contribution!

I'd like to see possibility to add encryption via CMK to ACR through this module, it would be really nice to have this feature in context of security.

For example something like this.

  customer_managed_key = {
    key_vault_resource_id              = key_vault_resource_id
    key_name                           = key_name
    user_assigned_identity_resource_id = user_assigned_identity_resource_id
  }

What do you think guys?

**Comment by prjelesi** [comment]
@pradorodriguez

**Comment by jchancellor-ms** [comment]
Picking this up and will add to next release

**Comment by jchancellor-ms** [comment]
@piotrkurylak - This has been added in v0.3.0 and an example has been published with this configured.  I will close this issue, but feel free to re-open it if you determine any functionality is missing.

**Comment by piotrkurylak** [comment]
@jchancellor-ms - really appreciate that, thank you.
