### ISSUE TITLE
[AVM Module Issue]: Resource naming condition incorrect

### ISSUE THREAD

**Issue by captainhook** [Azure/terraform-azurerm-avm-res-containerregistry-registry#64]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.0

### Description

The condition for Container Registry name is incorrect - https://github.com/Azure/terraform-azurerm-avm-res-containerregistry-registry/blob/4fb495d01b5380be083433e01003c79b05f277a5/variables.tf#L6

The correct condition as per Microsoft documentation is: "5-50 chars, Alphanumerics."

source: https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftcontainerregistry

**Comment by jchancellor-ms** [comment]
@captainhook - Thanks for reporting this issue.  I'll correct this in the next release.
