### ISSUE TITLE
implement diagnostic settings

### ISSUE THREAD

**Issue by rzand** [Azure/terraform-azurerm-avm-res-containerregistry-registry#70]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### (Optional) Module Version

0.1.0

### Description

The module accept the optional parameter diagnostic_settings but does not configure it.

**Comment by piotrkurylak** [comment]
Today I've realized this too. 

Contributors - Thanks in advance, appreciate that!
